### ISSUE TITLE
Cannot make 2mb or 4mb kickstart images

### ISSUE THREAD

**Issue by MadMungo** [reinauer/amiga-romy#2]
Stephan,

I can successfully make 1MB rom files but as soon as I try to make 2MB or 4MB rom files it errors out with the following

`madmungo@pop-os:~/Amig_Romy$ make kickstart TARGETS="A4000T" SIZES="4mb" VERSION="47.96"
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Gathering all files... Looking for Hyperion files
  * Can not find /home/madmungo/Downloads/AmigaOS-3.1.4-A3000.zip
  * Can not find /home/madmungo/Downloads/AmigaOS-3.1.4-A4000.zip
  * Can not find /home/madmungo/Downloads/AmigaOS-3.1.4-A4000T.zip
  * Can not find /home/madmungo/Downloads/AmigaOS-3.1.4.1-Update.zip
  * AmigaOS3.2CD.iso cached.
  * Can not find /home/madmungo/Downloads/kick_3.1.4.1.zip
  * Can not find /home/madmungo/Downloads/Update3.2.1.lha
Looking for add-on modules
  * arp40.2.lha cached.
  * vasm.tar.gz cached.
  * rnc_propack_source.zip cached.
  * hrtmon238.lha cached.
  * HRTModule236.lha cached.
  * pfs3aio.lha cached.
  * SFS.lha cached.
Looking for TF1260 drivers
  * ehide.tar.gz cached.
done
 * AmigaOS 3.1.4 A1200 files not found, skipping
 * AmigaOS 3.1.4 A3000 files not found, skipping
 * AmigaOS 3.1.4 A4000 files not found, skipping
 * AmigaOS 3.1.4 A4000T files not found, skipping
 * Unzipping AmigaOS 3.1.4.1 Update ...unzip:  cannot find or open /home/madmungo/Amig_Romy/archives/AmigaOS-3.1.4.1-Update.zip, /home/madmungo/Amig_Romy/archives/AmigaOS-3.1.4.1-Update.zip.zip or /home/madmungo/Amig_Romy/archives/AmigaOS-3.1.4.1-Update.zip.ZIP.
 ok
   * Unpacking * ... ok
 * Unpacking AmigaOS 3.2 ...[sudo] password for madmungo: 
Need root access
   * Unpacking diskdoctor ... ok
   * Unpacking install3.2 ... ok
 * Unpacking Arp 40.2 ok
 * Unzipping hrtmodule238 ... ok
 * Unpacking vasm ... ok
 * Unpacking rnc_propack_source ... ok
 * Unpacking PFS3AIO ok
 * Unpacking SmartFileSystem ok
 * Unpacking TF1260 ehide.device ok
Compiling vasm... ok.
Compiling rnc_propack_source... ok.
Compressing hrtmon data... ok.
Compiling HRTmodule 2.38 (16.02.2021)... ok.
Processing Kickstart 47.96 for A4000T (4mb)
Header 11144ef9 512
make: *** [Makefile:31: kickstart] Error 1
`
I also cannot create any other size rom for any other target for any version after successfully  creating a 1MB rom it errors with
make: *** [Makefile:31: kickstart] Error 2. This also happens if I try to make a rom after a reboot of the machine.

**Comment by reinauer** [comment]
Yeah, you need to install the latest git revision of amitools. Unfortunately Christian has not released a new version of amitools in the last year or so. that would include my fixes.

**Comment by MadMungo** [comment]
Ah OK.

So I am not a linux user, never had to compile stuff before. Are there
instructions on his github page for doing that? & do they include your
fixes?

Phillip

**Comment by reinauer** [comment]
[According to the author,](https://github.com/cnvogelg/amitools/issues/165) you can install it via 
```
pip install -U git+https://github.com/cnvogelg/amitools.git
```

**Comment by MadMungo** [comment]
Ok, thanks.

Yes that works for me. Can create all 3 sizes of rom now.
