### ISSUE TITLE
Cannot make kickstart images for a1200

### ISSUE THREAD

**Issue by mikketeus** [reinauer/amiga-romy#3]
Hi

I have a TF1260 and would very much like to autoboot from a faster IDE.
I can build A4000 images without any trouble, but not a1200 for some reason?

make kickstart TARGETS="A1200" VERSION=47.96 SIZES="1mb"
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Gathering all files... Looking for Hyperion files
  * Can not find /root/Downloads/AmigaOS-3.1.4-A3000.zip
  * Can not find /root/Downloads/AmigaOS-3.1.4-A4000.zip
  * Can not find /root/Downloads/AmigaOS-3.1.4-A4000T.zip
  * Can not find /root/Downloads/AmigaOS-3.1.4.1-Update.zip
  * AmigaOS3.2CD.iso cached.
  * Can not find /root/Downloads/kick_3.1.4.1.zip
  * Can not find /root/Downloads/Update3.2.1.lha
Looking for add-on modules
  * arp40.2.lha cached.
  * vasm.tar.gz cached.
  * rnc_propack_source.zip cached.
  * hrtmon238.lha cached.
  * HRTModule236.lha cached.
  * pfs3aio.lha cached.
  * SFS.lha cached.
Looking for TF1260 drivers
  * ehide.tar.gz cached.
done
 * AmigaOS 3.1.4 A1200 files not found, skipping
 * AmigaOS 3.1.4 A3000 files not found, skipping
 * AmigaOS 3.1.4 A4000 files not found, skipping
 * AmigaOS 3.1.4 A4000T files not found, skipping
 * Unzipping AmigaOS 3.1.4.1 Update ...unzip:  cannot find or open ~/dev/Github/amiga-romy/software/archives/AmigaOS-3.1.4.1-Update.zip,~/dev/Github/amiga-romy/software/archives/AmigaOS-3.1.4.1-Update.zip.zip or ~/dev/Github/amiga-romy/software/archives/AmigaOS-3.1.4.1-Update.zip.ZIP.
 ok
   * Unpacking * ... ok
 * Unpacking AmigaOS 3.2 ...Need root access
   * Unpacking diskdoctor ... ok
   * Unpacking install3.2 ... ok
 * Unpacking Arp 40.2 ok
 * Unzipping hrtmodule238 ... ok
 * Unpacking vasm ... ok
 * Unpacking rnc_propack_source ... ok
 * Unpacking PFS3AIO ok
 * Unpacking SmartFileSystem ok
 * Unpacking TF1260 ehide.device ok
Compiling vasm... ok.
Compiling rnc_propack_source... ok.
Compressing hrtmon data... ok.
Compiling HRTmodule 2.38 (16.02.2021)... ok.
Processing Kickstart 47.96 for A1200 (1mb)
Header 11144ef9 512
make: *** [Makefile:31: kickstart] Error 2

**Comment by mikketeus** [comment]
Nevermind, I did some chown's and used my normal user and it worked.

**Comment by reinauer** [comment]
Check out this one as well for installing the latest version of amitools
needed for larger rom images and some other features

https://github.com/reinauer/amiga-romy/issues/2#issuecomment-1034068938
