### ISSUE TITLE
 Assembly error for A1200

### ISSUE THREAD

**Issue by JV-Soft** [reinauer/amiga-romy#4]
I updated all packages .
Kickstart patch for A4000 and A4000T is made normally only with ROOT, Kickstart patch for A500, A1200, A3000 is an error, it doesn’t matter if there is a ROOT or not

For A4000 - 

am@jam-VirtualBox:~/amiga-romy/software$ sudo make kickstart TARGETS="A4000" VERSION=47.102 SIZES="1mb"
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Processing Kickstart 47.102 for A4000 (1mb)
Header 11144ef9 512
Header 11144ef9 512
Header 11144ef9 512
Success! Now write build/47.102/kick.a4000.47.102.1mb.LO.bin and build/47.102/kick.a4000.47.102.1mb.HI.bin to two 27C400 chips (A4000).

--------------------------------------------------------------------
For A1200 - 

jam@jam-VirtualBox:~/amiga-romy/software$ sudo make kickstart TARGETS="A1200" VERSION=47.96 SIZES="1mb"
[sudo] password for jam: 
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Processing Kickstart 47.96 for A1200 (1mb)
Header 11144ef9 512
make: *** [Makefile:31: kickstart] Error 2

------------------------------------------------------------------------------------

After a clean install -

jam@jam-VirtualBox:~/amiga-romy/software$ sudo make kickstart TARGETS="A1200" VERSION=47.96 SIZES="1mb"
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Gathering all files... Looking for Hyperion files
  * Can not find /root/Downloads/AmigaOS-3.1.4-A3000.zip
  * Can not find /root/Downloads/AmigaOS-3.1.4-A4000.zip
  * Can not find /root/Downloads/AmigaOS-3.1.4-A4000T.zip
  * Can not find /root/Downloads/AmigaOS-3.1.4.1-Update.zip
  * AmigaOS3.2CD.iso cached.
  * Can not find /root/Downloads/kick_3.1.4.1.zip
  * Update3.2.1.lha cached.
Looking for add-on modules
  * arp40.2.lha cached.
  * vasm.tar.gz cached.
  * rnc_propack_source.zip cached.
  * hrtmon238.lha cached.
  * HRTModule236.lha cached.
  * pfs3aio.lha cached.
  * SFS.lha cached.
Looking for TF1260 drivers
  * ehide.tar.gz cached.
done
 * AmigaOS 3.1.4 A1200 files not found, skipping
 * AmigaOS 3.1.4 A3000 files not found, skipping
 * AmigaOS 3.1.4 A4000 files not found, skipping
 * AmigaOS 3.1.4 A4000T files not found, skipping
 * Unzipping AmigaOS 3.1.4.1 Update ...unzip:  cannot find or open /home/jam/amiga-romy/software/archives/AmigaOS-3.1.4.1-Update.zip, /home/jam/amiga-romy/software/archives/AmigaOS-3.1.4.1-Update.zip.zip or /home/jam/amiga-romy/software/archives/AmigaOS-3.1.4.1-Update.zip.ZIP.
 ok
   * Unpacking * ... ok
 * Unpacking AmigaOS 3.2 ...Need root access
   * Unpacking diskdoctor ... ok
   * Unpacking install3.2 ... ok
 * Unpacking AmigaOS 3.2.1 Update ... ok
   * Unpacking DiskDoctor ... ok
   * Unpacking Update3.2.1 ... ok
 * Unpacking Arp 40.2 ok
 * Unzipping hrtmodule238 ... ok
 * Unpacking vasm ... ok
 * Unpacking rnc_propack_source ... ok
 * Unpacking PFS3AIO ok
 * Unpacking SmartFileSystem ok
 * Unpacking TF1260 ehide.device ok
Compiling vasm... cached.
Compiling rnc_propack_source... cached.
Compressing hrtmon data... cached.
Compiling HRTmodule 2.38 (16.02.2021)... cached.
Processing Kickstart 47.96 for A1200 (1mb)
Header 11144ef9 512
make: *** [Makefile:31: kickstart] Error 2

**Comment by JV-Soft** [comment]
I also wanted to say that after the error, only one file is created in the build / 47.96 folder, this is kick.a1200.47.96-512kb
I checked it, it's a working kickstart 47.96

**Comment by reinauer** [comment]
You need the latest version of amitools

`
pip install -U git+https://github.com/cnvogelg/amitools.git
`

**Comment by JV-Soft** [comment]
Updated amitools as you recommended, did not help

jam@jam-VirtualBox:~/amiga-romy/software$ make kickstart TARGETS="A1200" VERSION=47.96 SIZES="1mb"
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Processing Kickstart 47.96 for A1200 (1mb)
2022-07-26 23:44:18,628  ERROR       root        IO Error: [Errno 13] Permission denied: 'ArpLib40.2/arp.library'
make: *** [Makefile:31: kickstart] Error 1

With ROOT rights - 

jam@jam-VirtualBox:~/amiga-romy/software$ sudo make kickstart TARGETS="A1200" VERSION=47.96 SIZES="1mb"
[sudo] password for jam: 
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Processing Kickstart 47.96 for A1200 (1mb)
Header 11144ef9 512
make: *** [Makefile:31: kickstart] Error 2

**Comment by JV-Soft** [comment]
And again, the A4000 and A4000T are being made, but the rest are not - 

jam@jam-VirtualBox:~/amiga-romy/software$ sudo make kickstart TARGETS="A4000" VERSION=47.96 SIZES="1mb"
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Processing Kickstart 47.96 for A4000 (1mb)
Header 11144ef9 512
Header 11144ef9 512
Header 11144ef9 512
Success! Now write build/47.96/kick.a4000.47.96.1mb.LO.bin and build/47.96/kick.a4000.47.96.1mb.HI.bin to two 27C400 chips (A4000).

jam@jam-VirtualBox:~/amiga-romy/software$ sudo make kickstart TARGETS="A4000T" VERSION=47.96 SIZES="1mb"
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Processing Kickstart 47.96 for A4000T (1mb)
Header 11144ef9 512
Header 11144ef9 512
Header 11144ef9 512
Success! Now write build/47.96/kick.a4000t.47.96.1mb.LO.bin and build/47.96/kick.a4000t.47.96.1mb.HI.bin to two 27C400 chips (A4000T).

jam@jam-VirtualBox:~/amiga-romy/software$ sudo make kickstart TARGETS="A3000" VERSION=47.96 SIZES="1mb"
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Processing Kickstart 47.96 for A3000 (1mb)
Header 11144ef9 512
make: *** [Makefile:31: kickstart] Error 2
jam@jam-VirtualBox:~/amiga-romy/software$ sudo make kickstart TARGETS="A500" VERSION=47.96 SIZES="1mb"
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Processing Kickstart 47.96 for A500 (1mb)
Header 11144ef9 512
make: *** [Makefile:31: kickstart] Error 2
jam@jam-VirtualBox:~/amiga-romy/software$ sudo make kickstart TARGETS="A1200" VERSION=47.96 SIZES="1mb"
Checking the programs required for the build are installed...
ROMY 1MB/2MB/4MB Kickstart patcher

Fasten your seatbelts and hold your breath (no, better don't!)

Processing Kickstart 47.96 for A1200 (1mb)
Header 11144ef9 512
make: *** [Makefile:31: kickstart] Error 2

**Comment by reinauer** [comment]
Your first comment has files left over from running as root. You need to clean them out. The second post is once again using the wrong version of amitools. (probably because the new version is installed for the user but you are running as root again).

**Comment by JV-Soft** [comment]
Thank you very much for your work and support!

ср, 16 нояб. 2022 г. в 06:34, Stefan Reinauer ***@***.***>:
